/* ========================================
*
* Copyright University of Auckland, 2016
* All Rights Reserved
* UNPUBLISHED, LICENSED SOFTWARE.
*
* Metadata
* Written by    : Nathanaël Esnault
* Verified by   : N/A
* Creation date : 2016-03-05
* Version       : 1.0 (finished on ...)
* Modifications :
* Known bugs    :
*
*
* Possible Improvements
*
*
* Notes
*
*
* ========================================
*/

//This file is generated by a Matlab function V1.0, folder "Bathymetry", files "BathymetryGyrCalibration", etc

/*  Calibration Data  --> circular permutation consistency : xyz yzx zxy */

//Accelerometers
//----------------------------------------------------------------------------

#define KAx_0	0.281671416392885
#define KAx_1 	0.920800895409249
#define KAx_2 	9.016391798003533e-04
#define KAx_3 	7.266635419182036e-04
#define KAx_C 	-2.753760289808351e-04
#define KAx_P 	0.005386946192752
#define KAx_SC 	0.034219945578054
#define KAx_SP	0.004207881187701

#define KAy_0	0.050374215991455
#define KAy_1	0.683934021617439	 
#define KAy_2 	-3.582309898750121e-04
#define KAy_3   0.002930634774814
#define KAy_C   0.022137199289679
#define KAy_P   0.004521239191247
#define KAy_SC  -0.007353325113056
#define KAy_SP  -0.003561034966368


#define KAz_0	0.339201498805302
#define KAz_1   0.748887808162200
#define KAz_2   -0.004588053210677
#define KAz_3   0.002518849560898
#define KAz_C   0.019776267059128
#define KAz_P   0.004863005429704
#define KAz_SC  0.008206450365190
#define KAz_SP  0.009045708241308


//Gyroscopes
//----------------------------------------------------------------------------

#define KGx_0	0.0
#define KGx_1	1.0	 
#define KGx_2 	0.0
#define KGx_3   0.0
#define KGx_C   0.0
#define KGx_P   0.0
#define KGx_SC  0.0
#define KGx_SP  0.0

#define KGy_0	0.0
#define KGy_1	1.0 
#define KGy_2 	0.0
#define KGy_3   0.0
#define KGy_C   0.0
#define KGy_P   0.0
#define KGy_SC  0.0
#define KGy_SP  0.0


#define KGz_0	0.0
#define KGz_1   1.0
#define KGz_2   0.0
#define KGz_3   0.0
#define KGz_C   0.0
#define KGz_P   0.0
#define KGz_SC  0.0
#define KGz_SP  0.0

//Compass
//----------------------------------------------------------------------------

#define KCx_0	0.501013817027410
#define KCx_1 	46.756581602848880

#define KCy_0	-11.712800534171407
#define KCy_1 	49.624883553407700

#define KCz_0	-2.069836651557116
#define KCz_1 	47.534373435796226


/* [] END OF FILE */
